{
    'name': 'School Management System',
    'version': '18.0.1.0.0',
    'category': 'Education',
    'summary': 'Manage students, teachers and rooms',
    'depends': ['base', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/module_category.xml',
        'security/group.xml',
        'views/account_move_ext.xml',
        'views/res_partner_view.xml',
        'views/school_student_views.xml',
        'views/school_teacher_views.xml',
        'views/school_room_views.xml',
        'views/menu_views.xml',
        'wizard/student_teacher_wizard_view.xml',
    ],
    'installable': True,
    'application': True,
}
